# Generated by Django 5.2 on 2025-04-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
