# Generated by Django 5.2 on 2025-04-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(max_length=50, verbose_name='Ism familiya'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='grade',
            field=models.CharField(choices=[('5', '5-sinf'), ('6', '6-sinf'), ('7', '7-sinf'), ('8', '8-sinf'), ('9', '9-sinf')], max_length=50, verbose_name='Sinf'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=13, verbose_name='Tel. raqam'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='school',
            field=models.CharField(max_length=255, verbose_name='Maktab'),
        ),
    ]
